# ProxyDiscord Config File
# Make sure there is always a space after any :

# Bot token
token: bot-token-here

linking-secret: ')2z#*MR^BrGVygg7'

# Channel to accept !link requests from
linking-channel-id: '123456789'

# Role id the user needs to have to be allowed in
verify-role-id: '123456789'

# Permission to grant users who have verified
verified-permission: 'group.verified'

# Permission to allow bypassing the verification requirements
bypass-permission: 'discord.bypass'

# Server unverified players are allowed on to link/verify
unverified-server: 'waiting'

# Server to redirect newly verified players to, if their original destination is unknown
default-verified-server: 'waiting'

# Channel to log joins/leaves/chats etc in
log-channel-id: '123456789'

# Channel for annoucements, messages sent here will be shown in chat
announcement-channels:
  '610046112996261908':
    serverList: false
  '762327405758775317':
    serverList: true
    servers:
      - 'stresstest'

# Enable debug logging? Only useful if you are developing this plugin.
debug-enabled: false

# Time in seconds to wait before kicking unverified players
unverified-kick-time: 3600