# Bot token
token: bot-token-here

linking-secret: ')2z#*MR^BrGVygg7'

# Discord channel for the bot to listen for and respond to link attempts
linking-channel-id: '123456789'

# Discord roles that make a user "verified" and allowed to join the server
verified-role-ids:
 - '123456789'

# Permission to grant users who are verified
verified-permission: 'group.verified'

# Permission to allow bypassing the linking and role checks
bypass-permission: 'discord.bypass'

# Server to send players to, if they try to join a non-public server without meeting the requirements
linking-server: 'linking'

# Servers which players can join without linking or verifying
public-servers: []

# Server to redirect newly verified players to, if their original destination is unknown
default-verified-server: 'waiting'

# Channel to log joins/leaves/chats etc in
log-channel-id: '123456789'

# Channel for annoucements, messages sent here will be shown in chat
announcement-channels:
  '610046112996261908':
    serverList: false
  '762327405758775317':
    serverList: true
    servers:
      - 'stresstest'

# Whether to debug logging
debug-enabled: true
