# Bot token
token: bot-token-here

linking-secret: ')2z#*MR^BrGVygg7'

# Discord channel for the bot to listen for and respond to link attempts
linking-channel-id: '123456789'

# Discord roles that should be checked to determine if a player can join (is "verified")
# If no roles are defined, all players are considered verified
verified-role-ids:
 - '123456789'

# Permission to grant users who are verified
verified-permission: 'group.verified'

# Permission to allow bypassing the linking and role checks
bypass-permission: 'discord.bypass'

# Server to send players to, if they try to join a non-public server without meeting the requirements
linking-server: 'linking'

# Servers which players can join without linking or verifying
public-servers: []

# Server to redirect newly verified players to, if their original destination is unknown
default-verified-server: 'waiting'

# Channel to log joins/leaves/chats etc in
logging-channel-id: '123456789'

# Formats for logging various events
# Remove or empty to disable
logging-formats:
  date: '<dd-MM-yy HH:mm:ss>' # Used for [date] in other formats
  # In-game chat
  chat: |-
    ```md
    [date] [[server]][[player]]([discord_id]) [message]```
  # Messages sent in the discord logging channel. Useful for keeping the appearance of messages consistent
  discord-chat: |-
    ```md
    [DISCORD] [date] [[server]][[player]]([discord_id]) [message]```
  # Players joining the server
  join: |-
    ```md
    [date] [[server]][[player]]([discord_id]) has joined the network```
  # Players leaving the server
  leave: |-
    ```md
    [date] [[server]][[player]]([discord_id]) has left the network```
  # Commands run by players
  command: |-
    ```md
    [COMMAND] [date] [[server]][[player]]([discord_id]) [command]```

# Whether to delete messages sent in the discord logging channel
# Prevents duplicage messages if logging of messages sent from the discord side is enabled
logging-delete-sent-messages: true

# Channel for annoucements, messages sent here will be shown in chat
announcement-channels:
  '610046112996261908':
    serverList: false
  '762327405758775317':
    serverList: true
    servers:
      - 'stresstest'

# Whether to debug logging
debug-enabled: true
