# Settings for the discord bot itself
bot:
  token: # Bot token here

  # Activity to show in Discord
  activity-type: 'playing' # Valid values: playing, streaming, listening, watching, competing
  activity: 'Minecraft'

# Settings for linking discord accounts and verification
linking:
  secret: ')2z#*MR^BrGVygg7'

  # Discord channel for the bot to listen for and respond to link attempts
  discord-channel-id: '123456789'

  # Server to send players to for the linking and verification processes
  linking-server: 'linking'

  # Discord roles that should be checked to determine if a player can play on servers (is "verified")
  # If no roles are defined, all players are considered verified
  verified-role-ids: []

  # Permission to grant users who are verified
  verified-permission: 'group.verified'

  # Permission to allow bypassing verification
  bypass-permission: 'discord.bypass'

  # Server to send newly verified players to, if their original destination is unknown
  default-destination-server: 'hub'

  # Servers which players can join without being linked or verified
  public-servers: []

  # Whether to allow the !unlink bot command for unlinking from discord
  # If false, players will need to use /unlink in-game
  allow-discord-unlinking: false

# Discord roles to sync to luckperms groups
# Note that removing a group from this list will *not* remove it from players who have it. You will have to do this manually.
synced-roles: {}
  # 'roleid1': 'group1' # Single group
  # 'roleid2': # Multiple groups
  #   - 'group1'
  #   - 'group2'

# Whether to use velocity's events for logging.
# These can be disabled to avoid double-logging if you have another plugin using the API to log the same events.
events:
  use-command-event: true
  use-chat-event: true
  use-post-connect-event: true
  use-disconnect-event: true

# Settings for chat and event logging
logging:
  default: # Default settings which can be overridden for an individual log channel
    # Event types to log. Valid events are 'join', 'leave', 'command', 'chat', 'discord-chat'
    events:
      - 'join'
      - 'leave'
      - 'command'
      - 'chat'
      - 'discord-chat' # If enabled, messages sent by users on discord in the log channel will be deleted and then logged using the 'discord-chat' log format.

    # Optional list of servers to log, will log all server if not specified
    # Also controls which servers will see messages sent in the Discord channel
    # servers:
    # - server1
    # - server2

    # Whether the log is public
    # Not used by default, but other plugins using the API may avoid logging sensitive information in public channels
    public: true

    # Formats for logging various events
    formats:
      code-block: true # If true, will surround all log messages with ``` code blocks
      date: '<dd-MM-yy HH:mm:ss>' # Used for <date> in other formats
      # In-game chat
      chat: |-
        ```md
        <date> [<server>][<player>](<discord_mention>) <message>```
      # Messages sent in the discord logging channel. Useful for keeping the appearance of messages consistent
      discord-chat: |-
        ```md
        [DISCORD] <date> [<server>][<player>](<discord_mention>) <message>```
      discord-chat-ingame: '<green><bold>DISCORD> <reset><prefix><player><suffix><reset>: <message>'
      # Players joining the server
      join: |-
        ```md
        <date> [<server>][<player>](<discord_mention>) has joined <server>```
      # Players leaving the server
      leave: |-
        ```md
        <date> [<server>][<player>](<discord_mention>) has left <server>```
      # Commands run by players
      command: |-
        ```md
        [COMMAND] <date> [<server>][<player>](<discord_mention>) <command>```
  # 'channelid':
  #   events:
  #     - 'chat'
  #   servers:
  #     - 'server1'
  #     - 'server2'


# Settings for announcements
announcement-channels: {}
  # 'channelid' : {} # Messages sent in channel will be shown in all servers
  # 'channelid2': # Messages sent in channel will be shown in server1/server 2 only
  #   servers:
  #    - 'server1'
  #    - 'server2'

# Whether to debug logging
debug: true
