# Settings for the discord bot itself
bot:
  token: # Bot token here

  # Activity to show in Discord
  activity-type: 'playing' # Valid values: playing, streaming, listening, watching, competing
  activity: 'Minecraft'

# Settings for linking discord accounts and verification
linking:
  secret: ')2z#*MR^BrGVygg7'

  # Discord channel for the bot to listen for and respond to link attempts
  discord-channel-id: '123456789'

  # Server to send players to for the linking and verification processes
  linking-server: 'linking'

  # Discord roles that should be checked to determine if a player can play on servers (is "verified")
  # If no roles are defined, all players are considered verified
  verified-role-ids:
   - '123456789'

  # Permission to grant users who are verified
  verified-permission: 'group.verified'

  # Permission to allow bypassing verification
  bypass-permission: 'discord.bypass'

  # Server to send newly verified players to, if their original destination is unknown
  default-destination-server: 'hub'

  # Servers which players can join without being linked or verified
  public-servers: []

# Discord roles to sync to luckperms groups
# Note that removing a group from this list will *not* remove it from players who have it. You will have to do this manually.
synced-roles:
  # 'roleid1': 'group1' # Single group
  # 'roleid2': # Multiple groups
  #   - 'group1'
  #   - 'group2'

# Channel to log joins/leaves/chats etc in
logging-channel-id: '123456789'

# Formats for logging various events
# Remove or empty to disable
logging-formats:
  date: '<dd-MM-yy HH:mm:ss>' # Used for [date] in other formats
  # In-game chat
  chat: |-
    ```md
    [date] [[server]][[player]]([discord_id]) [message]```
  # Messages sent in the discord logging channel. Useful for keeping the appearance of messages consistent
  discord-chat: |-
    ```md
    [DISCORD] [date] [[server]][[player]]([discord_id]) [message]```
  # Players joining the server
  join: |-
    ```md
    [date] [[server]][[player]]([discord_id]) has joined the network```
  # Players leaving the server
  leave: |-
    ```md
    [date] [[server]][[player]]([discord_id]) has left the network```
  # Commands run by players
  command: |-
    ```md
    [COMMAND] [date] [[server]][[player]]([discord_id]) [command]```

# Whether to delete messages sent in the discord logging channel
# Prevents duplicage messages if logging of messages sent from the discord side is enabled
logging-delete-sent-messages: true

# Settings for announcements
announcement-channels:
  # 'channelid' : {} # Messages sent in channel will be shown in all servers
  # 'channelid2': # Messages sent in channel will be shown in server1/server 2 only
  #   servers:
  #    - 'server1'
  #    - 'server2'

# Whether to debug logging
debug: true
